name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: haskell-actions/setup@6037f33647c3f17758a2356c80fc4a53d7e0685d # v2
        id: setup-haskell
        with:
          ghc-version: '9.6.6'
          cabal-version: '3.10.3.0'
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: cabal-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: cabal-${{ runner.os }}-${{ runner.arch }}-
      - uses: browser-actions/setup-chrome@48ad923757ca74d66703209fe939badbdf80f2f4 # v2
        id: setup-chrome
        with:
          chrome-version: stable
      - run: sudo apt-get update && sudo apt-get install -y poppler-utils zlib1g-dev
      - run: make test
      - run: make evaluate
        env:
          CHROMIUM: ${{ steps.setup-chrome.outputs.chrome-path }}
